# Generated by Django 4.1.6 on 2023-02-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('auth_number', models.IntegerField(default=0)),
                ('is_success', models.BooleanField(default=False)),
            ],
        ),
    ]
