# Generated by Django 4.1.6 on 2023-02-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nick_name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('create_dt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
