# Generated by Django 4.1.6 on 2023-02-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('nick_name', models.TextField()),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('create_dt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
